import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const skillsDir = path.join(root, "skills");
const outFile = path.join(root, "data", "skills.js");

function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (/\.(md|json)$/i.test(entry.name)) out.push(full);
  }
  return out;
}

const entries = {};
for (const file of walk(skillsDir).sort()) {
  const rel = path.relative(skillsDir, file).replace(/\\/g, "/");
  entries[rel] = fs.readFileSync(file, "utf8");
}

const js =
  "// AUTO-GENERATED by scripts/build-content.mjs - do not edit by hand.\n" +
  "// Run: node scripts/build-content.mjs\n" +
  "window.SKILLS_CONTENT = " +
  JSON.stringify(entries) +
  ";\n";

fs.writeFileSync(outFile, js);
console.log(`Wrote ${Object.keys(entries).length} skills -> ${path.relative(root, outFile)}`);
